project:
  type: website

website:
  title: "Forecasting"
  navbar:
    right:
      - icon: github
        text: GitHub
        href: https://github.com/amyheather/forecasting

format:
  html:
    theme: [simplex, theme.scss]
    css: style.css
    toc: true